# Generated by Django 2.2 on 2022-04-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220426_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
    ]
