# Generated by Django 2.2 on 2022-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220427_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonusername',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
