# Generated by Django 2.2 on 2022-04-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220430_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='publish_count',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Новостей опубликовано'),
        ),
    ]
