# Generated by Django 2.2 on 2022-05-01 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220430_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='publish_count',
            field=models.CharField(blank=True, default=None, max_length=36, verbose_name='Новостей опубликовано'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification',
            field=models.BooleanField(default=False, verbose_name='Верифицырован'),
        ),
    ]
