# Generated by Django 2.2 on 2022-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20220503_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='publish_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
