# Generated by Django 2.2 on 2022-05-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_remove_profile_publish_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='profile',
            name='publish_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
