# Generated by Django 2.2 on 2022-05-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20220503_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_edit', 'может добавлять'),), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
