# Generated by Django 2.2 on 2022-05-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20220506_0402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('edit', 'может добавлять'),), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
