# Generated by Django 2.2 on 2022-05-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20220506_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_edit', 'может добавлять'),), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
