# Generated by Django 2.2 on 2022-05-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20220506_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(default='', max_length=15),
        ),
    ]
