# Generated by Django 2.2 on 2022-04-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0002_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
